"""check changes

Revision ID: 596895ab6ad5
Revises: 8099e684fe80
Create Date: 2026-09-15 10:06:55.306595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596895ab6ad5'
down_revision: Union[str, Sequence[str], None] = '8099e684fe80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sentences_user_id_srs_due', 'sentences', ['user_id', 'srs_due'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentences_user_id_srs_due', table_name='sentences')
    # ### end Alembic commands ###
