"""add srs fields to sentences

Revision ID: 8099e684fe80
Revises: b5feca403bbe
Create Date: 2026-09-15 09:49:15.128522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8099e684fe80'
down_revision: Union[str, Sequence[str], None] = 'b5feca403bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('srs_due', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    op.add_column('sentences', sa.Column('srs_interval_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sentences', sa.Column('srs_ease', sa.Float(), server_default='2.5', nullable=False))
    op.add_column('sentences', sa.Column('srs_reps', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sentences', sa.Column('srs_lapses', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sentences', sa.Column('srs_state', sa.Text(), server_default='new', nullable=False))
    op.create_check_constraint('ck_sentences_srs_state_valid', 'sentences', "srs_state in ('new','learning','review','relearning')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_sentences_srs_state_valid', 'sentences', type_='check')
    op.drop_column('sentences', 'srs_state')
    op.drop_column('sentences', 'srs_lapses')
    op.drop_column('sentences', 'srs_reps')
    op.drop_column('sentences', 'srs_ease')
    op.drop_column('sentences', 'srs_interval_days')
    op.drop_column('sentences', 'srs_due')
    # ### end Alembic commands ###
