"""add scenes table

Revision ID: d8480a86e514
Revises: 596895ab6ad5
Create Date: 2026-09-17 18:00:50.038288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8480a86e514'
down_revision: Union[str, Sequence[str], None] = '596895ab6ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('sentence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('padding_sentence_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('text_de', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('line_sentence_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('review_count_since_generated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenes_user_topic_generated', 'scenes', ['user_id', 'topic', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scenes_user_topic_generated', table_name='scenes')
    op.drop_table('scenes')
    # ### end Alembic commands ###
